[package]
name = "arc-auth-db"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
description = "Database identity and role provider plugin for Arc"

[dependencies]
arc-auth-core = { path = "../arc-auth-core", version = "0.8.2" }
arc-web = { path = "../arc-web", version = "0.8.2" }
argon2.workspace = true
async-trait.workspace = true
diesel.workspace = true
rand.workspace = true
rpassword.workspace = true
uuid.workspace = true
