#!/usr/bin/env bash
#
# Arc upgradeability drift guard.
#
# ADR 0002 defines machine-owned/generated files as safe to regenerate and
# unsafe to hand-edit. This script enforces the currently mechanical part of
# that boundary and is intentionally small enough to run often.
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT"

fail=0

check_generated_banner() {
  local file="$1"
  local generated_by="$2"
  local regenerate_hint="$3"

  if [ ! -f "$file" ]; then
    echo "MISSING GENERATED FILE: $file" >&2
    fail=1
    return
  fi

  if ! sed -n '1,3p' "$file" | grep -Fq "$generated_by"; then
    echo "MISSING GENERATED BANNER: $file must name $generated_by" >&2
    fail=1
  fi

  if ! sed -n '1,3p' "$file" | grep -Fq "$regenerate_hint"; then
    echo "MISSING REGENERATION HINT: $file must mention $regenerate_hint" >&2
    fail=1
  fi
}

echo "arc-check: checking generated-file ownership boundary..."

check_generated_banner \
  "config/benthos/generated/events.yaml" \
  "Generated by scripts/generate-benthos-config.mjs" \
  "make benthos-config"

if [ "$fail" -ne 0 ]; then
  echo "arc-check: FAILED - generated file banner checks failed." >&2
  exit 1
fi

npm run benthos:config:check

echo "arc-check: OK - generated files are fresh and carry ownership banners."
