#!/usr/bin/env bash
#
# Arc upgradeability drift guard.
#
# ADR 0002 defines machine-owned/generated files as safe to regenerate and
# unsafe to hand-edit. This script enforces the currently mechanical part of
# that boundary and is intentionally small enough to run often.
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT"

fail=0

check_generated_banner() {
  local file="$1"
  local generated_by="$2"
  local regenerate_hint="$3"

  if [ ! -f "$file" ]; then
    echo "MISSING GENERATED FILE: $file" >&2
    fail=1
    return
  fi

  if ! sed -n '1,3p' "$file" | grep -Fq "$generated_by"; then
    echo "MISSING GENERATED BANNER: $file must name $generated_by" >&2
    fail=1
  fi

  if ! sed -n '1,3p' "$file" | grep -Fq "$regenerate_hint"; then
    echo "MISSING REGENERATION HINT: $file must mention $regenerate_hint" >&2
    fail=1
  fi
}

forbid_path() {
  # Fail if a path that must not exist is present, per ADR 0002 ownership.
  local path="$1"
  local why="$2"
  if [ -e "$path" ]; then
    echo "OWNERSHIP VIOLATION: $path must not exist — $why" >&2
    fail=1
  fi
}

echo "arc-check: checking framework/app ownership boundary (ADR 0002)..."

# The framework crate must stay generic over the aggregate: no user-owned
# domain, services, or validation may live in arc-web.
forbid_path "crates/arc-web/src/domain" "user domain is app-owned; arc-web is generic over the aggregate"
forbid_path "crates/arc-web/src/services" "application services are app-owned"
forbid_path "crates/arc-web/src/validation" "application validation is app-owned"

# The Arc-owned runtime must not reappear inside the thin app (no re-fork of
# framework code, and no duplication of the modules that moved to arc-web).
forbid_path "crates/arc-app/src/http/middlewares" "framework middleware lives in arc-web"
forbid_path "crates/arc-app/src/websocket" "framework websocket transport lives in arc-web"
forbid_path "crates/arc-app/src/helpers/es_stack.rs" "the event-sourced stack lives in arc-web"
forbid_path "crates/arc-app/src/helpers/session.rs" "session helpers live in arc-web"
forbid_path "crates/arc-app/src/commands/serve.rs" "the serve bootstrap lives in arc-web"

echo "arc-check: checking publishable-crate file boundaries..."

publishable_crates=(
  crates/arc-core
  crates/arc-es-sqlite
  crates/arc-es-postgres
  crates/arc-es-nats
  crates/arc-web
)

if rg -n 'embed_migrations!\(\)' "${publishable_crates[@]}" --glob '*.rs'; then
  echo "PACKAGE VIOLATION: publishable crates must use an explicit crate-local migration path." >&2
  fail=1
fi

if rg -n 'embed_migrations!\("\.\.' "${publishable_crates[@]}" --glob '*.rs'; then
  echo "PACKAGE VIOLATION: publishable crates cannot embed migrations from outside their crate." >&2
  fail=1
fi

echo "arc-check: checking generated-file ownership boundary..."

check_generated_banner \
  "config/benthos/generated/events.yaml" \
  "Generated by scripts/generate-benthos-config.mjs" \
  "make benthos-config"

if [ "$fail" -ne 0 ]; then
  echo "arc-check: FAILED - ownership or package-boundary checks failed." >&2
  exit 1
fi

npm run benthos:config:check

echo "arc-check: OK - generated files are fresh and carry ownership banners."
