[package]
name = "arc-auth-admin"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
description = "Optional host-rendered browser administration for Arc authentication"

[dependencies]
arc-auth-core = { path = "../arc-auth-core", version = "0.8.1" }
arc-auth-session = { path = "../arc-auth-session", version = "0.8.1" }
arc-web = { path = "../arc-web", version = "0.8.1" }
actix-session.workspace = true
actix-web.workspace = true
async-trait.workspace = true
serde.workspace = true
tera.workspace = true
