[package]
name = "arc-auth-jwt"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
description = "Optional JWT API authentication plugin for Arc"

[dependencies]
arc-auth-core = { path = "../arc-auth-core", version = "0.7.1" }
arc-core = { path = "../arc-core", version = "0.7.1" }
arc-web = { path = "../arc-web", version = "0.7.1" }
actix-web.workspace = true
async-trait.workspace = true
serde.workspace = true
serde_json.workspace = true
